name: dep_guard
description: Dependency health and safe upgrade planning for Dart and Flutter projects.
version: 0.1.2
repository: https://github.com/tjoser/dep_guard.git
homepage: https://github.com/tjoser/dep_guard
issue_tracker: https://github.com/tjoser/dep_guard/issues
topics:
  - dependencies
  - cli
  - devtools
  - dart
  - flutter
executables:
  dep_guard: dep_guard
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.5.0
  yaml: ^3.1.2
  http: ^1.2.1
  pub_semver: ^2.1.4
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
